name       : openjazz
version    : 160214
release    : 2
source     :
    - http://www.alister.eu/jazz/oj/OpenJazz-src-160214.zip : 8178731e005188a8e87174af26f767b7a1815c06b3bd9b8156440ecea4d7b10a
    - http://image.dosgamesarchive.com/games/jazz.zip : ed025415c0bc5ebc3a41e7a070551bdfdfb0b65b5314241152d8bd31f87c22da
license    : GPL-2.0
component  : games.platformer
summary    : Jazz Jackrabbit reborn on Linux
description: |
    Jazz JAckrabbit reborn on Linux
builddeps  :
    - pkgconfig(libmodplug)
    - pkgconfig(sdl)
setup      : |
    %reconfigure
build      : |
    %make USE_MODPLUG=1
install    : |-
    %make_install
    install -D -m 00644 $pkgfiles/openjazz.desktop $installdir/usr/share/applications/openjazz.desktop
    install -D -m 00644 $pkgfiles/openjazz.png $installdir/usr/share/pixmaps/openjazz.png
    mkdir jazz
    unzip $sources/jazz.zip -d jazz/
    cp jazz/* $installdir/usr/share/openjazz/
    rm -f $installdir/usr/share/openjazz/*.{EXE,DOC,DIZ}
    cd $installdir/usr/share/openjazz
    mv BONUS.PSM bonus.psm
    mv ENDLEVEL.PSM endlevel.psm
    mv MENUSNG.PSM menusng.psm
    mv SONG0.PSM song0.psm
    mv SONG3.PSM song3.psm
    mv SONG17.PSM song17.psm
